/*
  StarRuby Version [HEADER]
  vr 1.0.0
  */
#ifndef STARRUBY_VERSION_H
#define STARRUBY_VERSION_H

#define STRB_VERSION_MAJOR 0
#define STRB_VERSION_MINOR 5
#define STRB_VERSION_PATCH 4
#define STRB_VERSION_BUILD 0
//#define STRB_VERSION_STRING #STRB_VERSION_MAJOR "." #STRB_VERSION_MINOR "." #STRB_VERSION_PATCH "." #STRB_VERSION_BUILD
#define STRB_VERSION_STRING "0.5.4.0"

#endif
